### ISSUE TITLE
[Bug]: Invalid object passing validation

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#1049]
### What happened?

I created an ElectricalSeries then deleted electrodes and it validates with no errors. electrodes is required, so it should throw an error when this dataset is missing.

### Steps to Reproduce

```python
import h5py
from pynwb.testing.mock.ecephys import mock_ElectricalSeries

from pynwb import NWBHDF5IO, NWBFile
from datetime import datetime
from dateutil.tz import tzlocal

nwbfile = NWBFile(
    session_description="my first synthetic recording",
    identifier="EXAMPLE_ID",
    session_start_time=datetime.now(tzlocal()),
    session_id="LONELYMTN",
)

mock_ElectricalSeries(nwbfile=nwbfile)

with NWBHDF5IO("test_electrodes.nwb", "w") as io:
    io.write(nwbfile)

with h5py.File("test_electrodes.nwb", "r+") as f:
    del f["acquisition"]["ElectricalSeries"]["electrodes"]

# python -m pynwb.validate test_electrodes.nwb
```

### Operating System

macOS

### Python Executable

Conda

### Python Version

3.12

**Comment by bendichter** [comment]
@rly, any idea what might be going on here?

**Comment by CodyCBakerPhD** [comment]
Does the API-based validation through the NWB Inspector catch anything?

**Comment by bendichter** [comment]
<img width="254" alt="image" src="https://github.com/hdmf-dev/hdmf/assets/844306/ed930de2-4d1d-4d56-bad8-9de748740a61">

**Comment by bendichter** [comment]
@CodyCBakerPhD 

yes, on initialization of the ElectricalSeries object:

```
(base) MacBook-Pro-108:py_isx bendichter$ nwbinspector /Users/bendichter/Library/Application\ Support/JetBrains/PyCharmCE2021.3/scratches/test_electrodes2.nwb
Traceback (most recent call last):
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/objectmapper.py", line 1258, in construct
    obj = self.__new_container__(cls, builder.source, parent, builder.attributes.get(self.__spec.id_key()),
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/objectmapper.py", line 1271, in __new_container__
    obj.__init__(**kwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 663, in func_call
    pargs = _check_args(args, kwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 656, in _check_args
    raise ExceptionType(msg)
TypeError: ElectricalSeries.__init__: missing argument 'electrodes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bendichter/opt/miniconda3/bin/nwbinspector", line 8, in <module>
    sys.exit(inspect_all_cli())
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/nwbinspector/nwbinspector.py", line 271, in inspect_all_cli
    messages = list(
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/nwbinspector/nwbinspector.py", line 403, in inspect_all
    nwbfile = robust_s3_read(io.read)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/nwbinspector/utils.py", line 173, in robust_s3_read
    raise exc
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/nwbinspector/utils.py", line 168, in robust_s3_read
    return command(*command_args, **command_kwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 664, in func_call
    return func(args[0], **pargs)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/pynwb/__init__.py", line 304, in read
    file = super().read(**kwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/backends/hdf5/h5tools.py", line 479, in read
    return super().read(**kwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 664, in func_call
    return func(args[0], **pargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/backends/io.py", line 60, in read
    container = self.__manager.construct(f_builder)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 664, in func_call
    return func(args[0], **pargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/manager.py", line 284, in construct
    result = self.__type_map.construct(builder, self, None)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 664, in func_call
    return func(args[0], **pargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/manager.py", line 795, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 664, in func_call
    return func(args[0], **pargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/objectmapper.py", line 1228, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/objectmapper.py", line 1157, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/objectmapper.py", line 1208, in __get_sub_builders
    ret.update(self.__get_subspec_values(sub_builder, subspec, manager))
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/objectmapper.py", line 1157, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/objectmapper.py", line 1200, in __get_sub_builders
    sub_builder = self.__flatten(sub_builder, subspec, manager)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/objectmapper.py", line 1213, in __flatten
    tmp = [manager.construct(b) for b in sub_builder]
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/objectmapper.py", line 1213, in <listcomp>
    tmp = [manager.construct(b) for b in sub_builder]
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 664, in func_call
    return func(args[0], **pargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/manager.py", line 280, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 664, in func_call
    return func(args[0], **pargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/manager.py", line 795, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 664, in func_call
    return func(args[0], **pargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/objectmapper.py", line 1262, in construct
    raise ConstructError(builder, msg) from ex
hdmf.build.errors.ConstructError: (root/acquisition/ElectricalSeries GroupBuilder {'attributes': {'comments': 'no comments', 'description': 'description', 'filtering': 'filtering', 'namespace': 'core', 'neurodata_type': 'ElectricalSeries', 'object_id': '10fd9470-4cc8-4a9e-9b29-0f171b4bc3dd'}, 'groups': {}, 'datasets': {'data': root/acquisition/ElectricalSeries/data DatasetBuilder {'attributes': {'conversion': 1.0, 'offset': 0.0, 'resolution': -1.0, 'unit': 'volts'}, 'data': <Closed HDF5 dataset>}, 'starting_time': root/acquisition/ElectricalSeries/starting_time DatasetBuilder {'attributes': {'rate': 30000.0, 'unit': 'seconds'}, 'data': 0.0}}, 'links': {}}, "Could not construct ElectricalSeries object due to: ElectricalSeries.__init__: missing argument 'electrodes'")
```

**Comment by bendichter** [comment]
or were you asking me to run something else?

**Comment by bendichter** [comment]
[test_electrodes2.nwb.zip](https://github.com/hdmf-dev/hdmf/files/14103681/test_electrodes2.nwb.zip)

**Comment by CodyCBakerPhD** [comment]
I hoped the Inspector would make it a bit further; what if you do

```python
import pynwb

with NWBHDF5IO(path="test_electrodes2.nwb", mode="r") as io:
    pynwb.validate(io=io)
```

and how does it compare to

```python
import pynwb

pynwb.validate(paths=["test_electrodes2.nwb"])
```

**Comment by CodyCBakerPhD** [comment]
Or I suppose you should capture output from each call...

```python
results = pynwb.validate(...)
print(results)
```

**Comment by bendichter** [comment]
@CodyCBakerPhD nothing using any of those methods

**Comment by rly** [comment]
> @rly, any idea what might be going on here?

I'm not sure. Nothing stands out in the [code](https://github.com/hdmf-dev/hdmf/blob/dev/src/hdmf/validate/validator.py#L477). I'll dig into it.

**Comment by rly** [comment]
Well, this looks bad. It looks like a lot of things are not being validated. For `nwbfile.acquisition`, the spec says that `NWBDataInterface` is allowed:
`{'doc': 'Acquired, raw data.', 'quantity': '*', 'neurodata_type_inc': 'NWBDataInterface'}`

The validator validates the `ElectricalSeries` builder against that spec and the spec for `'neurodata_type_def': 'NWBDataInterface'`:
`{'doc': 'An abstract data type for a generic container storing collections of data, as opposed to metadata.', 'neurodata_type_inc': 'NWBContainer', 'neurodata_type_def': 'NWBDataInterface'}
`

but does not validate the `ElectricalSeries` builder against the `ElectricalSeries` spec itself.

I'll see if I can fix this in the next week or two.
