### ISSUE TITLE
error instantiating many classes in pynwb

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#153]
```python
from pynwb.misc import Units
Units()
```

```python
Traceback (most recent call last):
  File "/Users/bendichter/dev/pynwb/my_test.py", line 3, in <module>
    Units()
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/misc.py", line 155, in __init__
    call_docval_func(super(Units, self).__init__, kwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 327, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/core.py", line 942, in __init__
    id = ElementIdentifiers('id')
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/core.py", line 401, in __init__
    call_docval_func(super(ElementIdentifiers, self).__init__, kwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 327, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/core.py", line 281, in __init__
    call_docval_func(super(NWBData, self).__init__, kwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 327, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/core.py", line 34, in __init__
    call_docval_func(super(NWBBaseType, self).__init__, kwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 327, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 436, in func_call
    raise_from(ExceptionType(msg), None)
  File "<string>", line 3, in raise_from
TypeError: None is not allowed for 'data' (expected 'ndarray, list, tuple, Dataset, HDMFDataset or data', not None)
```

hdmf.git@9b6848f535bc7aa34b840cdae0ef202347ea618e#egg=hdmf

pynwb.git@ab493464ddc65df4724b5d82354e31fadc91880d#egg=pynwb

**Comment by bendichter** [comment]
@rly can you reproduce this?

**Comment by rly** [comment]
@bendichter Using the dev branch of PyNWB with the dev branch of HDMF is temporarily broken until https://github.com/NeurodataWithoutBorders/pynwb/pull/1061 is merged

**Comment by rly** [comment]
#1061 required several major code refactorings in other repos before it could be tested and merged. Should happen later today.
