### ISSUE TITLE
dtype argument breaks DataChunkIterator

### ISSUE THREAD

**Issue by luiztauffer** [hdmf-dev/hdmf#285]
Reporting what seems to be a bug on DataChunkIterator.
`pynwb==1.2.1` and `hdmf==1.6.0`

Take the example below:
If I don't pass `dtype` to DataChunkIterator, the data gets saved correctly as integers. 
If I pass `dtype` it breaks.

```python
from datetime import datetime
from hdmf.data_utils import DataChunkIterator
from pynwb import NWBFile, NWBHDF5IO
from pynwb.image import TimeSeries
import numpy as np

nwbfile = NWBFile('Test', '123', datetime.now())

data = np.random.randint(10, size=(1000, 3, 3)).astype('int16')
def data_gen(data):
    chunk = 0
    while chunk < 1000:
        out = data[chunk, :, :]
        chunk += 1
        yield out

iter_data = DataChunkIterator(
    data=data_gen(data),
    iter_axis=0,
    dtype=np.dtype('int16')
)

ts = TimeSeries(
    name='Test',
    data=iter_data,
    starting_time=0.,
    rate=10.,
    unit='V'
)

nwbfile.add_acquisition(ts)

with NWBHDF5IO('out.nwb', 'w') as io:
    io.write(nwbfile)

with NWBHDF5IO('out.nwb', 'r') as io:
    nwbfile = io.read()
    print(nwbfile.acquisition)
```

This yields:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\hdmf\backends\hdf5\h5tools.py in __setup_chunked_dset__(cls, parent, name, data, options)
    979         try:
--> 980             dset = parent.create_dataset(name, **io_settings)
    981         except Exception as exc:

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\h5py\_hl\group.py in create_dataset(self, name, shape, dtype, data, **kwds)
    135         with phil:
--> 136             dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    137             dset = dataset.Dataset(dsid)

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\h5py\_hl\dataset.py in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times, external, track_order, dcpl)
    139         chunks, compression, compression_opts, shuffle, fletcher32,
--> 140         maxshape, scaleoffset, external)
    141 

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\h5py\_hl\filters.py in fill_dcpl(plist, shape, dtype, chunks, compression, compression_opts, shuffle, fletcher32, maxshape, scaleoffset, external)
    132     rq_tuple(chunks, 'chunks')
--> 133     rq_tuple(maxshape, 'maxshape')
    134 

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\h5py\_hl\filters.py in rq_tuple(tpl, name)
    128             raise TypeError('"%s" argument must be None or a sequence object' % name)
--> 129         if len(tpl) != len(shape):
    130             raise ValueError('"%s" must have same rank as dataset shape' % name)

TypeError: object of type 'NoneType' has no len()

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
<ipython-input-9-61a15eb6c024> in <module>
     32 
     33 with NWBHDF5IO('out.nwb', 'w') as io:
---> 34     io.write(nwbfile)
     35 
     36 with NWBHDF5IO('out.nwb', 'r') as io:

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    451 
    452             if is_method:
--> 453                 return func(args[0], **parsed['args'])
    454             else:
    455                 return func(**parsed['args'])

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\hdmf\backends\hdf5\h5tools.py in write(self, **kwargs)
    267 
    268         cache_spec = popargs('cache_spec', kwargs)
--> 269         call_docval_func(super().write, kwargs)
    270         if cache_spec:
    271             ref = self.__file.attrs.get(SPEC_LOC_ATTR)

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\hdmf\utils.py in call_docval_func(func, kwargs)
    341 def call_docval_func(func, kwargs):
    342     fargs, fkwargs = fmt_docval_args(func, kwargs)
--> 343     return func(*fargs, **fkwargs)
    344 
    345 

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    451 
    452             if is_method:
--> 453                 return func(args[0], **parsed['args'])
    454             else:
    455                 return func(**parsed['args'])

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\hdmf\backends\io.py in write(self, **kwargs)
     42         container = popargs('container', kwargs)
     43         f_builder = self.__manager.build(container, source=self.__source)
---> 44         self.write_builder(f_builder, **kwargs)
     45 
     46     @abstractmethod

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    451 
    452             if is_method:
--> 453                 return func(args[0], **parsed['args'])
    454             else:
    455                 return func(**parsed['args'])

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\hdmf\backends\hdf5\h5tools.py in write_builder(self, **kwargs)
    534         f_builder, link_data, exhaust_dci = getargs('builder', 'link_data', 'exhaust_dci', kwargs)
    535         for name, gbldr in f_builder.groups.items():
--> 536             self.write_group(self.__file, gbldr, exhaust_dci=exhaust_dci)
    537         for name, dbldr in f_builder.datasets.items():
    538             self.write_dataset(self.__file, dbldr, link_data, exhaust_dci=exhaust_dci)

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    451 
    452             if is_method:
--> 453                 return func(args[0], **parsed['args'])
    454             else:
    455                 return func(**parsed['args'])

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\hdmf\backends\hdf5\h5tools.py in write_group(self, **kwargs)
    694             for subgroup_name, sub_builder in subgroups.items():
    695                 # do not create an empty group without attributes or links
--> 696                 self.write_group(group, sub_builder, exhaust_dci=exhaust_dci)
    697         # write all datasets
    698         datasets = builder.datasets

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    451 
    452             if is_method:
--> 453                 return func(args[0], **parsed['args'])
    454             else:
    455                 return func(**parsed['args'])

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\hdmf\backends\hdf5\h5tools.py in write_group(self, **kwargs)
    699         if datasets:
    700             for dset_name, sub_builder in datasets.items():
--> 701                 self.write_dataset(group, sub_builder, exhaust_dci=exhaust_dci)
    702         # write all links
    703         links = builder.links

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    451 
    452             if is_method:
--> 453                 return func(args[0], **parsed['args'])
    454             else:
    455                 return func(**parsed['args'])

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\hdmf\backends\hdf5\h5tools.py in write_dataset(self, **kwargs)
    892             # Iterative write of a data chunk iterator
    893             elif isinstance(data, AbstractDataChunkIterator):
--> 894                 dset = self.__setup_chunked_dset__(parent, name, data, options)
    895                 self.__dci_queue.append((dset, data))
    896             # Write a regular in memory array (e.g., numpy array, list etc.)

c:\users\luiz\anaconda3\envs\jaeger_nwb\lib\site-packages\hdmf\backends\hdf5\h5tools.py in __setup_chunked_dset__(cls, parent, name, data, options)
    980             dset = parent.create_dataset(name, **io_settings)
    981         except Exception as exc:
--> 982             raise Exception("Could not create dataset %s in %s" % (name, parent.name)) from exc
    983         return dset
    984 

Exception: Could not create dataset data in /acquisition/Test
```

**Comment by oruebel** [comment]
@luiztauffer Thanks for including the example code.  I'll try to take a look today.

**Comment by rly** [comment]
Returning to this after a long delay. This MWE no longer produces this error with the latest HDMF. Instead, it produces this error:
```
Traceback (most recent call last):
  File "/Users/rly/Documents/NWB/hdmf/src/hdmf/backends/hdf5/h5tools.py", line 1379, in __setup_chunked_dset__
    dset = parent.create_dataset(name, **io_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rly/mambaforge/envs/dev/lib/python3.11/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rly/mambaforge/envs/dev/lib/python3.11/site-packages/h5py/_hl/dataset.py", line 104, in make_new_dset
    dcpl = filters.fill_dcpl(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/rly/mambaforge/envs/dev/lib/python3.11/site-packages/h5py/_hl/filters.py", line 159, in fill_dcpl
    raise TypeError(
TypeError: Empty datasets don't support chunk/filter options
```

because you cannot create an empty chunked dataset without specifying a shape or maxshape to initialize the dataset with. Solutions to that include 1) specify a shape or maxshape, 2) do not specify a dtype so that the first chunk is read and the shape of the first chunk is used as the initial shape, or 3) call `iter_data.next()` to read the first chunk explicitly so that the shape of that chunk is used as the initial shape. 

Please re-open if this is still an issue.
