### ISSUE TITLE
Cannot write references when root container is not called "root"

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#359]
## Description

The below code creates a table, adds an indexed column, adds a row, and writes the table to file. 

```python
from hdmf.common import DynamicTable, get_manager
from hdmf.backends.hdf5 import HDF5IO

table = DynamicTable('table0', 'an example table')
table.add_column('qux', 'a boolean column', index=True)
table.add_row(qux=[True, True])

filename = 'test.h5'
manager = get_manager()
with HDF5IO(filename, manager=manager, mode='w') as io:
    io.write(table)

with HDF5IO(filename, manager=manager, mode='r') as io:
    io.read()
```

Reading the file results in:

```
Traceback (most recent call last):
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\backends\hdf5\h5tools.py", line 592, in __add_refs
    call()
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\backends\hdf5\h5tools.py", line 718, in _filler
    obj.attrs[key] = self.__get_ref(value)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 560, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\backends\hdf5\h5tools.py", line 1157, in __get_ref
    return self.__file[path].ref
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\Ryan\Miniconda3\envs\dev\lib\site-packages\h5py\_hl\group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (component not found)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_table.py", line 11, in <module>
    io.write(table)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 560, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\backends\hdf5\h5tools.py", line 302, in write
    call_docval_func(super().write, kwargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 404, in call_docval_func
    return func(*fargs, **fkwargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 560, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\backends\io.py", line 44, in write
    self.write_builder(f_builder, **kwargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 560, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\backends\hdf5\h5tools.py", line 574, in write_builder
    self.__add_refs()
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\backends\hdf5\h5tools.py", line 595, in __add_refs
    raise RuntimeError('Unable to resolve reference')
RuntimeError: Unable to resolve reference
```

## Environment

    Python Executable: Python
    Python Version: 3.7
    Operating System: Windows
    HDMF Version: dev

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
Oh, actually, the code fails on write.

I think I know the cause and have a semi-working solution where `ReferenceBuilder`s are created at the end of the build process, similar to how references are added to the h5py at the end of the write process.

**Comment by rly** [comment]
Fun little bug -- if the root container is not called "root", then references are not added correctly because of this code:
https://github.com/hdmf-dev/hdmf/blob/dev/src/hdmf/backends/hdf5/h5tools.py#L774

In NWB, `NWBFile.name` is forced to be set to 'root'.
