### ISSUE TITLE
get_class nameless LinkSpec

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#465]
`get_class` fails when a `LinkSpec` has no `name`.

**Comment by rly** [comment]
This is still broken:

```yaml
groups:
- neurodata_type_def: TestType1
  neurodata_type_inc: Container
  doc: Test Type

- neurodata_type_def: TestType2
  neurodata_type_inc: Container
  doc: Test Type
  links:
  - target_type: TestType1
    doc: geometry
```
```yaml
namespaces:
- doc: test extension
  name: test_link
  version: 0.1.0
  schema:
  - namespace: core
  - source: test_link.extensions.yaml
```
```python
from pynwb import load_namespaces, get_class

load_namespaces('test_link.namespace.yaml')
TestType1 = get_class('TestType1', 'test_link')
TestType2 = get_class('TestType2', 'test_link')
```

Error:
```
Traceback (most recent call last):
  File "test_link_extension.py", line 7, in <module>
    TestType2 = get_class('TestType2', 'test_link')
  File "C:\Users\Ryan\miniconda3\envs\dev\lib\site-packages\hdmf\utils.py", line 584, in func_call
    return func(**pargs)
  File "c:\users\ryan\documents\nwb\pynwb\src\pynwb\__init__.py", line 186, in get_class
    return __TYPE_MAP.get_dt_container_cls(neurodata_type, namespace)
  File "C:\Users\Ryan\miniconda3\envs\dev\lib\site-packages\hdmf\utils.py", line 580, in func_call
    return func(args[0], **pargs)
  File "C:\Users\Ryan\miniconda3\envs\dev\lib\site-packages\hdmf\build\manager.py", line 526, in get_dt_container_cls
    cls = self.__class_generator.generate_class(data_type, spec, parent_cls, attr_names, self)
  File "C:\Users\Ryan\miniconda3\envs\dev\lib\site-packages\hdmf\utils.py", line 580, in func_call
    return func(args[0], **pargs)
  File "C:\Users\Ryan\miniconda3\envs\dev\lib\site-packages\hdmf\build\classgenerator.py", line 55, in generate_class
    if not spec.is_inherited_spec(field_spec):
  File "C:\Users\Ryan\miniconda3\envs\dev\lib\site-packages\hdmf\utils.py", line 580, in func_call
    return func(args[0], **pargs)
  File "C:\Users\Ryan\miniconda3\envs\dev\lib\site-packages\hdmf\spec\spec.py", line 1014, in is_inherited_spec
    name = spec.data_type_def
AttributeError: 'LinkSpec' object has no attribute 'data_type_def'
```

**Comment by rly** [comment]
This is fixed now.
