### ISSUE TITLE
get_class failure

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#466]
## Description

The following type definition cannot be auto-generated using `get_class`

```python
TestType = GroupSpec(
        data_type_def='TestType',
        data_type_inc='Container',
        doc='TestType',
        groups=[
            GroupSpec(
                name='geometry',
                doc='geometry',
                datasets=[
                    DatasetSpec(
                        name='nodes',
                        doc='nodes',
                        dtype='float',
                        shape=(None, 3)
                    )
                ]
            )
        ]
    )
```
the following error is thrown:

```python
Traceback (most recent call last):
  File "/Users/bendichter/dev/ndx-scratch/src/pynwb/ndx_scratch/__init__.py", line 26, in <module>
    TestType = get_class('TestType', 'ndx-scratch')
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 565, in func_call
    return func(**pargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/__init__.py", line 187, in get_class
    return __TYPE_MAP.get_container_cls(namespace, neurodata_type)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/manager.py", line 658, in get_container_cls
    d = self.__get_cls_dict(parent_cls, fields, spec.name, spec.default_name)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/manager.py", line 581, in __get_cls_dict
    dtype = self.__get_type(field_spec)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/manager.py", line 481, in __get_type
    if spec.shape is None and spec.dims is None:
AttributeError: 'NWBGroupSpec' object has no attribute 'shape'
```

**Comment by rly** [comment]
This is fixed with HDMF 2.5.
