### ISSUE TITLE
ValueError: Field 'description' cannot be defined in FRETSeries. It already exists on base class ImageSeries.

### ISSUE THREAD

**Issue by luiztauffer** [hdmf-dev/hdmf#501]
I created an extension for ImageSeries, [FRETSeries](https://github.com/catalystneuro/ndx-fret/blob/master/src/spec/create_extension_spec.py)
it was working well until recently, and it still creates the objects and saves a nwb file with them correctly. But now I’m getting an error on read:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-10d8120c3cf3> in <module>
      5 fpath = os.path.join(r'out.nwb')
      6 io = pynwb.NWBHDF5IO(fpath, 'r', load_namespaces=True)
----> 7 nwb = io.read()
      8 nwb2widget(nwb)
      9 

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\backends\hdf5\h5tools.py in read(self, **kwargs)
    418                                        % (self.source, self.__mode))
    419         try:
--> 420             return call_docval_func(super().read, kwargs)
    421         except UnsupportedOperation as e:
    422             if str(e) == 'Cannot build data. There are no values.':  # pragma: no cover

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\utils.py in call_docval_func(func, kwargs)
    421 def call_docval_func(func, kwargs):
    422     fargs, fkwargs = fmt_docval_args(func, kwargs)
--> 423     return func(*fargs, **fkwargs)
    424 
    425 

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    578             def func_call(*args, **kwargs):
    579                 pargs = _check_args(args, kwargs)
--> 580                 return func(args[0], **pargs)
    581         else:
    582             def func_call(*args, **kwargs):

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\backends\io.py in read(self, **kwargs)
     39             # TODO also check that the keys are appropriate. print a better error message
     40             raise UnsupportedOperation('Cannot build data. There are no values.')
---> 41         container = self.__manager.construct(f_builder)
     42         return container
     43 

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    578             def func_call(*args, **kwargs):
    579                 pargs = _check_args(args, kwargs)
--> 580                 return func(args[0], **pargs)
    581         else:
    582             def func_call(*args, **kwargs):

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\build\manager.py in construct(self, **kwargs)
    280                 # we are at the top of the hierarchy,
    281                 # so it must be time to resolve parents
--> 282                 result = self.__type_map.construct(builder, self, None)
    283                 self.__resolve_parents(result)
    284             self.prebuilt(result, builder)

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    578             def func_call(*args, **kwargs):
    579                 pargs = _check_args(args, kwargs)
--> 580                 return func(args[0], **pargs)
    581         else:
    582             def func_call(*args, **kwargs):

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\build\manager.py in construct(self, **kwargs)
    957             raise ValueError('No ObjectMapper found for builder of type %s' % dt)
    958         else:
--> 959             return obj_mapper.construct(builder, build_manager, parent)
    960 
    961     @docval({"name": "container", "type": AbstractContainer, "doc": "the container to convert to a Builder"},

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    578             def func_call(*args, **kwargs):
    579                 pargs = _check_args(args, kwargs)
--> 580                 return func(args[0], **pargs)
    581         else:
    582             def func_call(*args, **kwargs):

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\build\objectmapper.py in construct(self, **kwargs)
   1208         cls = manager.get_cls(builder)
   1209         # gather all subspecs
-> 1210         subspecs = self.__get_subspec_values(builder, self.spec, manager)
   1211         # get the constructor argument that each specification corresponds to
   1212         const_args = dict()

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\build\objectmapper.py in __get_subspec_values(self, builder, spec, manager)
   1137                         ret[subspec] = self.__flatten(sub_builder, subspec, manager)
   1138             # now process groups and datasets
-> 1139             self.__get_sub_builders(groups, spec.groups, manager, ret)
   1140             self.__get_sub_builders(datasets, spec.datasets, manager, ret)
   1141         elif isinstance(spec, DatasetSpec):

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\build\objectmapper.py in __get_sub_builders(self, sub_builders, subspecs, manager, ret)
   1188                 if dt is None:
   1189                     # recurse
-> 1190                     ret.update(self.__get_subspec_values(sub_builder, subspec, manager))
   1191                 else:
   1192                     ret[subspec] = manager.construct(sub_builder)

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\build\objectmapper.py in __get_subspec_values(self, builder, spec, manager)
   1137                         ret[subspec] = self.__flatten(sub_builder, subspec, manager)
   1138             # now process groups and datasets
-> 1139             self.__get_sub_builders(groups, spec.groups, manager, ret)
   1140             self.__get_sub_builders(datasets, spec.datasets, manager, ret)
   1141         elif isinstance(spec, DatasetSpec):

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\build\objectmapper.py in __get_sub_builders(self, sub_builders, subspecs, manager, ret)
   1180                 sub_builder = builder_dt.get(dt)
   1181                 if sub_builder is not None:
-> 1182                     sub_builder = self.__flatten(sub_builder, subspec, manager)
   1183                     ret[subspec] = sub_builder
   1184             else:

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\build\objectmapper.py in __flatten(self, sub_builder, subspec, manager)
   1193 
   1194     def __flatten(self, sub_builder, subspec, manager):
-> 1195         tmp = [manager.construct(b) for b in sub_builder]
   1196         if len(tmp) == 1 and not subspec.is_many():
   1197             tmp = tmp[0]

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\build\objectmapper.py in <listcomp>(.0)
   1193 
   1194     def __flatten(self, sub_builder, subspec, manager):
-> 1195         tmp = [manager.construct(b) for b in sub_builder]
   1196         if len(tmp) == 1 and not subspec.is_many():
   1197             tmp = tmp[0]

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    578             def func_call(*args, **kwargs):
    579                 pargs = _check_args(args, kwargs)
--> 580                 return func(args[0], **pargs)
    581         else:
    582             def func_call(*args, **kwargs):

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\build\manager.py in construct(self, **kwargs)
    276             if parent_builder is not None:
    277                 parent = self._get_proxy_builder(parent_builder)
--> 278                 result = self.__type_map.construct(builder, self, parent)
    279             else:
    280                 # we are at the top of the hierarchy,

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    578             def func_call(*args, **kwargs):
    579                 pargs = _check_args(args, kwargs)
--> 580                 return func(args[0], **pargs)
    581         else:
    582             def func_call(*args, **kwargs):

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\build\manager.py in construct(self, **kwargs)
    952         if build_manager is None:
    953             build_manager = BuildManager(self)
--> 954         obj_mapper = self.get_map(builder)
    955         if obj_mapper is None:
    956             dt = builder.attributes[self.namespace_catalog.group_spec_cls.type_key()]

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    578             def func_call(*args, **kwargs):
    579                 pargs = _check_args(args, kwargs)
--> 580                 return func(args[0], **pargs)
    581         else:
    582             def func_call(*args, **kwargs):

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\build\manager.py in get_map(self, **kwargs)
    872             data_type = self.get_builder_dt(obj)
    873             namespace = self.get_builder_ns(obj)
--> 874             container_cls = self.get_cls(obj)
    875         # now build the ObjectMapper class
    876         mapper = self.__mappers.get(container_cls)

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    578             def func_call(*args, **kwargs):
    579                 pargs = _check_args(args, kwargs)
--> 580                 return func(args[0], **pargs)
    581         else:
    582             def func_call(*args, **kwargs):

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\build\manager.py in get_cls(self, **kwargs)
    805         if namespace is None:
    806             raise ValueError("No namespace found for builder %s" % builder.path)
--> 807         return self.get_container_cls(namespace, data_type)
    808 
    809     @docval({'name': 'spec', 'type': (DatasetSpec, GroupSpec), 'doc': 'the parent spec to search'},

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    578             def func_call(*args, **kwargs):
    579                 pargs = _check_args(args, kwargs)
--> 580                 return func(args[0], **pargs)
    581         else:
    582             def func_call(*args, **kwargs):

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\build\manager.py in get_container_cls(self, **kwargs)
    690             spec = self.__ns_catalog.get_spec(namespace, data_type)
    691             if isinstance(spec, GroupSpec):
--> 692                 self.__resolve_child_container_classes(spec, namespace)
    693 
    694             dt_hier = self.__ns_catalog.get_hierarchy(namespace, data_type)

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\build\manager.py in __resolve_child_container_classes(self, spec, namespace)
    735         for child_spec in (spec.groups + spec.datasets):
    736             if child_spec.data_type_inc is not None:
--> 737                 self.get_container_cls(namespace, child_spec.data_type_inc)
    738             elif child_spec.data_type_def is not None:
    739                 self.get_container_cls(namespace, child_spec.data_type_def)

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    578             def func_call(*args, **kwargs):
    579                 pargs = _check_args(args, kwargs)
--> 580                 return func(args[0], **pargs)
    581         else:
    582             def func_call(*args, **kwargs):

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\build\manager.py in get_container_cls(self, **kwargs)
    728                                  + str(e)
    729                                  + " Please define that type before defining '%s'." % name)
--> 730             cls = ExtenderMeta(str(data_type), bases, d)
    731             self.register_container_type(namespace, data_type, cls)
    732         return cls

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\utils.py in __init__(cls, name, bases, classdict)
    753         it = (a for a in it if hasattr(a, cls.__preinit))
    754         for func in it:
--> 755             func(name, bases, classdict)
    756         super().__init__(name, bases, classdict)
    757         it = (getattr(cls, n) for n in dir(cls))

c:\users\luiz\anaconda3\envs\env_jaeger\lib\site-packages\hdmf\container.py in __gather_fields(cls, name, bases, classdict)
    135                     if field_name in base_fields:
    136                         raise ValueError("Field '%s' cannot be defined in %s. It already exists on base class %s."
--> 137                                          % (field_name, cls.__name__, base_cls.__name__))
    138                 # prepend field specs from base class to fields list of this class
    139                 all_fields_conf[0:0] = base_cls.get_fields_conf()

ValueError: Field 'description' cannot be defined in FRETSeries. It already exists on base class ImageSeries.
```

**Comment by rly** [comment]
Could you include a link or paste of your test code?

I ran `python test.py` in ndx-fret and got a different unexpected error:
```
Traceback (most recent call last):
  File "test.py", line 49, in <module>
    print(nwb.acquisition['acceptor'])
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 929, in __getitem__
    return super().__getitem__(key)
KeyError: 'acceptor'
```

**Comment by luiztauffer** [comment]
You can test with this: https://github.com/catalystneuro/ndx-fret/blob/master/src/pynwb/ndx_fret/test.py
Weirdly, this script runs without errors. Now if after creating the file you run something like this, you should be able reproduce the error:
```python
import pynwb

io = pynwb.NWBHDF5IO('test_fret.nwb', 'r', load_namespaces=True)
nwbfile = io.read()
```

I checked that if you import FRET before reading, `from ndx_fret import FRET, FRETSeries`, the problem goes away.

**Comment by rly** [comment]
Thanks for testing this out. I'll take a look.
