### ISSUE TITLE
Cannot access all EnumData contents on read

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#595]
## Description

`tvt_mask` is a column of type `EnumData`

```
> table[:, 'tvt_mask']
array(['train', 'train'], dtype='<U5')
> read_table[:, 'tvt_mask']
*** TypeError: Indexing elements must be in increasing order
> read_table.tvt_mask[:]
*** TypeError: Indexing elements must be in increasing order
```

## Environment

    Python Executable: Conda
    Python Version: Python 3.8
    Operating System: Windows
    HDMF Version: 2.5.1

## Checklist

- [x] Have you ensured the bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by ajtritt** [comment]
This is still an issue. Below is an example exposing this in more detail (done using HDMF Version: 3.14.6)

### Example code: 
```python 
import numpy as np
from hdmf.common import DynamicTable, EnumData, get_hdf5io

# Create EnumData column
# Define the possible enum values
enum_values = ['red', 'green', 'blue', 'yellow']

# Create data using indices that map to the enum values
data_indices = np.array([0, 1, 2, 1, 3, 0, 2])  # indices into enum_values

# Create EnumData object
enum_column = EnumData(
    name='color_column',
    description='Colors as enumerated data',
    data=data_indices,
    elements=enum_values
)

# Create a DynamicTable with the EnumData column
table = DynamicTable(
    name='my_table',
    description='Example table with enum data',
    columns=[enum_column],
    colnames=['color_column']
)


# Write to HDF5 file
filename = 'example_enum_data.h5'
with get_hdf5io(filename, 'w') as io:
    io.write(table)

print("Data written to HDF5 file")

# Read back from HDF5 file
io = get_hdf5io(filename, 'r')
read_table = io.read()

print("Data read back from HDF5 file")

# Access the EnumData column
enum_col = read_table['color_column']

# Read data from the EnumData column
print("Enum elements:", enum_col.elements)
print("Raw indices:", enum_col.data[:])
print("Resolved values:", [enum_col.elements[i] for i in enum_col.data[:]])

# You can also access individual values
print("First value:", enum_col.elements[enum_col.data[0]])
print("Read all data:", enum_col[:])
```

### Output:
```
Data written to HDF5 file
Data read back from HDF5 file
Enum elements: <hdmf.common.table.VectorData object at 0x11fd15110>
Raw indices: [0 1 2 1 3 0 2]
Resolved values: ['red', 'green', 'blue', 'green', 'yellow', 'red', 'blue']
First value: red
Traceback (most recent call last):
  File "/Users/ajtritt/projects/nwb/hdmf.git/enum_data_broken.py", line 51, in <module>
    print("Read all data:", enum_col[:])
                            ~~~~~~~~^^^
  File "path-to-site-packages/hdmf/common/table.py", line 1609, in __getitem__
    return self.get(arg, index=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path-to-site-packages/hdmf/common/table.py", line 1642, in get
    return self._get_helper(idx, index=index, join=join, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path-to-site-packages/hdmf/common/table.py", line 1622, in _get_helper
    ret = np.asarray(self.elements.get(idx.ravel(), **kwargs)).reshape(idx.shape)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path-to-site-packages/hdmf/common/table.py", line 61, in get
    return super().get(key)
           ^^^^^^^^^^^^^^^^
  File "path-to-site-packages/hdmf/container.py", line 1012, in get
    return self.data[args]
           ~~~~~~~~~^^^^^^
  File "path-to-site-packages/hdmf/utils.py", line 1217, in __getitem__
    bytes_arr = self.dset[args]
                ~~~~~~~~~^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "path-to-site-packages/h5py/_hl/dataset.py", line 854, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path-to-site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_selector.pyx", line 282, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 215, in h5py._selector.Selector.apply_args
TypeError: Indexing elements must be in increasing order
```
