### ISSUE TITLE
[Bug]: DeprecationWarning on `import hdmf.common`

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#826]
### What happened?

Importing `hdmf.common` directly or through any package that does so, e.g., through `import pynwb`, results in the below DeprecationWarning regarding pkg_resources.

See also https://github.com/matplotlib/matplotlib/issues/25244

This does not appear to be an issue with HDMF, but perhaps we should catch and ignore this particular warning.

### Steps to Reproduce

```shell
python -W error::DeprecationWarning
Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hdmf
>>> import hdmf.common
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rly/mambaforge/envs/test/lib/python3.10/site-packages/hdmf/common/__init__.py", line 193, in <module>
    __resources = __get_resources()
  File "/Users/rly/mambaforge/envs/test/lib/python3.10/site-packages/hdmf/common/__init__.py", line 74, in __get_resources
    from pkg_resources import resource_filename
  File "/Users/rly/mambaforge/envs/test/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3258, in <module>
    def _initialize_master_working_set():
  File "/Users/rly/mambaforge/envs/test/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3232, in _call_aside
    f(*args, **kwargs)
  File "/Users/rly/mambaforge/envs/test/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3283, in _initialize_master_working_set
    tuple(dist.activate(replace=False) for dist in working_set)
  File "/Users/rly/mambaforge/envs/test/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3283, in <genexpr>
    tuple(dist.activate(replace=False) for dist in working_set)
  File "/Users/rly/mambaforge/envs/test/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2804, in activate
    declare_namespace(pkg)
  File "/Users/rly/mambaforge/envs/test/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2298, in declare_namespace
    warnings.warn(msg, DeprecationWarning, stacklevel=2)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

The specific package name in the warning changes depending on the environment. I can also get:
Deprecated call to `pkg_resources.declare_namespace('ruamel')`.

The same error occurs if I just do:
python -Werror -c "import pkg_resources"
```

### Traceback

```shell
See above
```

### Operating System

macOS

### Python Executable

Conda

### Python Version

3.10

### Package Versions

Clean Python 3.10 environment installed with conda-forge. Then clean `pip install hdmf`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by rly** [comment]
Try avoiding using pkg_resources - see example with importlib.resources: https://github.com/flyingcircusio/pycountry/pull/155/files

**Comment by mavaylon1** [comment]
I believe this is related to #822
