### ISSUE TITLE
load_namespaces feature is broken

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#95]
1) Bug

With the current dev branch of hdmf, loading any extension with the `NWBHDF5IO` flag `load_namespaces=True` results in the following error:

```python
from pynwb import NWBHDF5IO

with NWBHDF5IO('test_maze.nwb', 'r', load_namespaces=True) as io:
    nwb2 = io.read()
``` 

```python
/Users/bendichter/anaconda3/envs/dev_pynwb/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/Users/bendichter/dev/hdmf/src/hdmf/spec/namespace.py:452: UserWarning: ignoring namespace 'core' because it already exists
  warn("ignoring namespace '%s' because it already exists" % ns['name'])
Traceback (most recent call last):
  File "/Users/bendichter/dev/ndx-maze/src/pynwb/ndx_maze/test2.py", line 5, in <module>
    with NWBHDF5IO('test_maze.nwb', 'r', load_namespaces=True) as io:
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 388, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/__init__.py", line 216, in __init__
    super(NWBHDF5IO, self).load_namespaces(tm, path)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 388, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/backends/hdf5/h5tools.py", line 109, in load_namespaces
    d.update(namespace_catalog.load_namespaces('namespace', reader=reader))
ValueError: dictionary update sequence element #0 has length 8; 2 is required
```

For testing, you can use this file: https://drive.google.com/file/d/1iPAokMkr3a4uRlxUZtXQ7LY2gJRb3uG3/view?usp=sharing

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by bendichter** [comment]
@t-b it looks like your changes here 484e6fdc63853ce18a1a336111cd3053309f5dcd are causing the issue

**Comment by bendichter** [comment]
@ajtritt, is there a convenient way to clear a loaded namespace? If I want to test out `NWBHDF5IO` with the `load_namespaces=True` flag and have them actually build from the namespace, I might first need to unload that namespace, which is presumably stored in global variables somewhere. Is there a convenient way to do that? This bug went unnoticed because that's not very easy to do in a test script right now, or if it is I don't know how.
